# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Use custom format
format = '''
[->>](cyan) $sudo$username $os $time
$directory $package $git_branch $git_commit $git_metrics
[~~>](blue ) '''

right_format ="""$all""" 
# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10
 
command_timeout = 1000

palette = 'onedark'

[palettes.onedark]
white = "#abb2bf"
black = "#282c34"
gray = "#5c6370"
red = "#ef596f"
orange = "#d19a66"
blue = "#61afef"
green = "#89ca78"
yellow = "#e5c07b"
purple = "#d55fde"
cyan = "#2bbac5"
light_gray = "#bbbbbb"

# Disable the package module, hiding it from the prompt completely
[character]
success_symbol = "[✔](bold green)"
error_symbol = "[✘](bold red)"
[package]
disabled = false

[sudo]
disabled = false
format = "[$symbol]($style)"
symbol ="󱑷 "
style ="bold yellow"

[username]
format = "[$user]($style)"
show_always = true

[os]
disabled = false
format = "[$symbol]($style) "
style = "yellow"

[os.symbols]
Fedora = ""
Arch = "󰣇"
Manjaro = "󱘊 "
Pop = ""
Debian = "󰣚"

[time]
disabled = false
format = "[ $time]($style) "
time_format = "%k:%M"
style = "bold cyan"

[directory]
style = 'italic purple'
truncation_symbol = '...'

[git_branch]
format = "[$symbol $branch(:$remote_branch)]($style)"
style = "red"
symbol = ""

[git_commit]
disabled = false
format = "[ $hash$tag]($style)"
tag_disabled = false
tag_symbol = " 󰓹 "
style = "red"

[git_metrics]
disabled = false
format = "([ $added]($added_style) )([ $deleted]($deleted_style))"
added_style = "green"
deleted_style = "red"

[python]
symbol = '󰌠 '
pyenv_version_name = true

[ruby]
symbol = '󰴭 '

[rust]
symbol = '󱘗 '

[c]
symbol = ' '

[docker_context]
symbol = '󰡨 '

[haskell]
symbol = '󰲒 '

[java]
symbol = '󰬷 '

[kotlin]
symbol = '󱈙 '

[kubernetes]
symbol = '󱃾 '

[localip]
ssh_only = false
format = '[@$localipv4]($style) '
style = "bold green underline"
disabled = false

[lua]
symbol = '󰢱 '

[terraform]
symbol = '󱁢 '

[conda]
ignore_base = false
