complete --command spicetify --exclusive --condition __fish_use_subcommand --arguments apply --description "Apply customization"
complete --command spicetify --exclusive --condition __fish_use_subcommand --arguments backup --description "Start backup and preprocessing app files"
complete --command spicetify --exclusive --condition __fish_use_subcommand --arguments restore --description "Restore Spotify to original state"
complete --command spicetify --exclusive --condition __fish_use_subcommand --arguments clear --description "Clear current backup files"
complete --command spicetify --exclusive --condition __fish_use_subcommand --arguments enable-devtools --description "Enable Spotify's developer tools"
complete --command spicetify --exclusive --condition __fish_use_subcommand --arguments refresh --description "Refresh the theme's CSS, JS, colors, and assets"
complete --command spicetify --exclusive --condition __fish_use_subcommand --arguments restart --description "Restart Spotify client"

complete --command spicetify --short-option q --long-option quiet --description "Quiet mode"
complete --command spicetify --short-option s --long-option style --require-parameter --description "Path to .css style file"
complete --command spicetify --short-option e --long-option extension --require-parameter --description "Path to .js extension file"
complete --command spicetify --short-option a --long-option app --require-parameter --description "Path to custom app"
complete --command spicetify --short-option n --long-option no-restart --description "Do not restart Spotify after running commands"
complete --command spicetify --short-option l --long-option live-refresh --description "Auto-reload Spotify when changes are made to any custom component"
complete --command spicetify --short-option c --long-option config --description "Print config file path and quit"
complete --command spicetify --short-option h --long-option help --description "Print help and exit"
complete --command spicetify --short-option v --long-option version --description "Print version number and quit"
