-- disable netrw at the very start of your init.lua (strongly advised)
vim.g.loaded_netrw = 1
vim.g.loaded_netrwPlugin = 1
vim.g.netrw_use_noswf= 0

require("user.options")
require("user.keymaps")
require("user.plugins")
require("user.colorscheme")
require("user.nvimtree")
require("user.cmp")
require("user.lsp")
require("user.cokeline")
require("user.lualine")
require("user.telescope")
require("user.image")
require("user.treesitter")
require("user.autopairs")
require("user.gitsigns")
require("user.alpha")
require("user.peek")
require("user.biscuits")
require("user.baleia")
-- require("user.modicator")
require("user.toggleterm")
require('mini.cursorword').setup()
require('mini.animate').setup()
require("user.masonti")

vim.api.nvim_set_hl(0, 'NormalMode', {fg = "#89ca78", bold = true})
vim.api.nvim_set_hl(0, 'InsertMode', {fg = "#61afef", bold = true})
vim.api.nvim_set_hl(0, 'ReplaceMode', {fg = "#ef596f", bold = true})
vim.api.nvim_set_hl(0, 'CommandMode', {fg = "#d55fde", bold = true})
vim.api.nvim_set_hl(0, 'VisualMode', {fg = "#e5c07b", bold = true})
