# Sample config file
---
theme:
  active: "189, 146, 248"  # current playing song in list
  banner: "138, 233, 252"  # the "spotify-tui" banner on launch
  error_border: "255, 84, 84"  # error dialog border
  error_text: "255, 84, 84"  # error message text  hint: Yellow # hint text in errors
  hovered: "255, 84, 84"  # hovered pane border
  inactive: "84, 84, 84"  # borders of inactive panes
  playbar_background: "68, 71, 90"  # background of progress bar
  playbar_progress: "255, 120, 197"  # filled-in part of the progress bar
  playbar_progress_text: "255, 120, 197"  # song length and time played/left indicator in the progress bar
  playbar_text: "189, 146, 248"  # artist name in player pane
  selected: "189, 146, 248"  # a) selected pane border, b) hovered item in list, & c) track title in player
  text: "187, 187, 187"  # text in panes
  header: White  # header text in panes (e.g. 'Title', 'Artist', etc.)

behavior:
  volume_increment: 5
  # Determines the text icon to display next to "liked" Spotify items, such as
  # liked songs and albums, or followed artists. Can be any length string.
  # These icons require a patched nerd font.
  liked_icon: 󰣐
  shuffle_icon: 󰒟
  repeat_track_icon: 󰑘
  repeat_context_icon: 󰑖
  playing_icon: 󰐊
  paused_icon: 󰏤

keybindings:
  # Key stroke can be used if it only uses two keys:
  # ctrl-q works,
  # ctrl-alt-q doesn't.
  back: "ctrl-q"

  jump_to_album: "a"

  # Shift modifiers use a capital letter (also applies with other modifier keys
  # like ctrl-A)
  jump_to_artist_album: "A"

  manage_devices: "d"
  decrease_volume: "-"
  increase_volume: "+"
  toggle_playback: " "
  seek_backwards: "<"
  seek_forwards: ">"
  next_track: "n"
  previous_track: "p"
  copy_song_url: "c"
  copy_album_url: "C"
  help: "?"
  shuffle: "ctrl-s"
  repeat: "r"
  search: "/"
  audio_analysis: "v"
  jump_to_context: "o"
  basic_view: "B"
  add_item_to_queue: "z"
