plugin_dirs = [
    '/hdd/Bottles/Plugin-Alliance-Manager/drive_c/Program Files/Common Files/VST3',
    '/hdd/Bottles/Spitfire/drive_c/Program Files/Common Files/VST3',
    '/home/zombie/.wine/drive_c/Program Files/Common Files/VST2',
    '/home/zombie/.wine/drive_c/Program Files/Common Files/VST3',
    '/home/zombie/.wine/drive_c/Program Files/Steinberg/VstPlugins',
    '/home/zombie/.wine/drive_c/Program Files/VSTPlugins',
]
vst2_location = 'centralized'
no_verify = false
blacklist = []

[last_known_config]
wine_version = 'wine-8.20 (Staging)'
yabridge_host_hash = -2648076669449613275
